name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}

    steps:
      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/github_ec2_deploy
          chmod 600 ~/.ssh/github_ec2_deploy
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Deploy en EC2
        run: |
          ssh -i ~/.ssh/github_ec2_deploy ubuntu@$EC2_HOST << 'EOF'
            cd ~/Curso-NestJS
            pkill -f "node dist/main.js" || true
            git pull origin main
            yarn install --frozen-lockfile
            yarn build
            nohup yarn start:prod > app.log 2>&1 &
          EOF
